---

name: test
on:
  workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Debug"
              run: |
                echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
                echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
                echo "GITHUB_SHA: $GITHUB_SHA"
                echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
                echo "${{ toJson(vars) }}"
